### ISSUE TITLE
Animation Handler ist nicht performant

### ISSUE THREAD

**Issue by SBird1337** [SBird1337/source_of_the_sovereign#17]
Der Standard Animation Handler (U.a. Hesperia) ist nicht unbedingt Ressourcensparend.

**Comment by ipatix** [comment]
Meinst du die Meteoranimation?

**Comment by SBird1337** [comment]
Nein, ich meine den Tileset Animator, der u.a. für Blumen, Rauch und den ganzen Spaß verantwortlich ist.

**Comment by ipatix** [comment]
Wo ist der dazugehörige Code? Könnte mir das mal ansehen.

**Comment by SBird1337** [comment]
https://github.com/SBird1337/source_of_the_sovereign/blob/master/src/overworld/tileset_animation/main_animator.c#L22

**Comment by ipatix** [comment]
Yo, kein Wunder dass das Lahm ist. 2 Divisionen und nen printf, was permanent aufgerufen wird. Ich fix das mal.

**Comment by ipatix** [comment]
https://github.com/SBird1337/source_of_the_sovereign/commit/63d15b1acc01cf9ca8161a034abb8b16e200fc54
