### ISSUE TITLE
Titelscreen Pokémon Cry

### ISSUE THREAD

**Issue by Dragonflysots** [SBird1337/source_of_the_sovereign#28]
Im Titelscreen ist immernoch das Geschrei von Glurak zu hören, müssen wir fixen.

**Comment by Dragonflysots** [comment]
@ipatix @SBird1337 ist leider nur auf FF beschränkt, Deoxys bzw. die Äonen liegen drüber.

**Comment by ipatix** [comment]
7bae74f4493b71f9f39ba993a0192a374ba7b3b2
