### ISSUE TITLE
Titelscreen Länge

### ISSUE THREAD

**Issue by Dragonflysots** [SBird1337/source_of_the_sovereign#29]
Wir müssen dauer die Dauer des Titelscreen erhöhen, damit man die Music länger hören kann. Die nötige suche wird bald beginnen, wo da steht.

**Comment by Dragonflysots** [comment]
@SBird1337 Auch nur auf 0x33 beschränkt irgendwie ka.

**Comment by ipatix** [comment]
7bae74f4493b71f9f39ba993a0192a374ba7b3b2

**Comment by ipatix** [comment]
@Dragonflysots War übrigens auf 0xFFFFFFFF Frames beschränkt und das Ändern kein großer Akt.
