### ISSUE TITLE
Hilfemenu und das Intro neugestalten

### ISSUE THREAD

**Issue by Dragonflysots** [SBird1337/source_of_the_sovereign#31]
Das Intro muss geskippt werden bzw. ein eigenes her.
![pkmn_sots_01](https://user-images.githubusercontent.com/27623565/36499804-afe51058-1742-11e8-989f-bd50607afc7b.png)

**Comment by SBird1337** [comment]
resolved with 293bf29e8e8525200aaf890084d506227d2b05bd
