### ISSUE TITLE
Animationsfarbe anpassen

### ISSUE THREAD

**Issue by Dragonflysots** [SBird1337/source_of_the_sovereign#36]
![pkmn_sots_08](https://user-images.githubusercontent.com/27623565/36501743-3478e574-1748-11e8-997b-624d23dd19a0.png)

*An dieser Stelle auch mal die restlichen Animationen einfügen, habe sie ja net umsonst gespritet. xD

**Comment by ipatix** [comment]
Sind die starken Wellen für einen See nicht ein bisschen übertrieben?

**Comment by SBird1337** [comment]
Ich hab das mal nur implementiert, man kann natürlich die Geschwindigkeit ein bissl runterdrehen, ansonsten muss man aber die Frames selber bearbeiten (assets/images/tileset_animation)

**Comment by SBird1337** [comment]
rework...
