### ISSUE TITLE
Urbania City: Script für die Höhle der Wächter

### ISSUE THREAD

**Issue by SBird1337** [SBird1337/source_of_the_sovereign#67]
![pkmn_sots_27](https://user-images.githubusercontent.com/3799173/36632482-6d77f7b6-1987-11e8-9c82-ed3e6d109c35.png)
Dieser Script sollte automatisch starten, es ist nicht unbedingt inhärent, dass man, um weiterzukommen, die Statue anklicken muss.

**Comment by Dragonflysots** [comment]
Wie genau soll es "automatisch" starten?
