### ISSUE TITLE
Status Menü: Einige Pokémon glitchen

### ISSUE THREAD

**Issue by SBird1337** [SBird1337/source_of_the_sovereign#71]
![pkmn_sots_01](https://user-images.githubusercontent.com/3799173/36632539-0fb344f4-1988-11e8-8df0-0b172fa36377.png)
Nicht bei allen, mir momentan bekannt:

- Wattzapf
- Dartiri
- Flabébé

**Comment by Dragonflysots** [comment]
Fähigkeitennamen war das Problem.
