### ISSUE TITLE
Durchgangshäuser passen nicht zusammen:

### ISSUE THREAD

**Issue by ipatix** [SBird1337/source_of_the_sovereign#77]
Rechtes Übergangshaus von Carun City:

von rechts siehts propertionsmäßig korrekt aus
![pkmn_sots_13](https://user-images.githubusercontent.com/8502545/36703730-591fee18-1b5d-11e8-89e5-ce52ec67196e.png)
:

von links hat das Haus einerseits ne falsche Farbe und ist leicht versetzt:
![pkmn_sots_14](https://user-images.githubusercontent.com/8502545/36703751-6d572310-1b5d-11e8-96a9-b879772be90e.png)

**Comment by SBird1337** [comment]
rework
