### ISSUE TITLE
Space im Namen des Superschutzes?

### ISSUE THREAD

**Issue by ipatix** [SBird1337/source_of_the_sovereign#78]
![pkmn_sots_15](https://user-images.githubusercontent.com/8502545/36708005-32c9d1d4-1b71-11e8-915a-d7be42448419.png)

Bin mir nicht sicher was kaputt ist, aber das passt nicht.

**Comment by SBird1337** [comment]
https://github.com/SBird1337/source_of_the_sovereign/issues/46 sollte das lösen.

**Comment by SBird1337** [comment]
Closed, da #46 gefixt.
