### ISSUE TITLE
Baum des Lebens: Falsche Gehdaten?

### ISSUE THREAD

**Issue by ipatix** [SBird1337/source_of_the_sovereign#79]
![pkmn_sots_16](https://user-images.githubusercontent.com/8502545/36708131-df9b7502-1b71-11e8-98ef-ddb815f8672d.png)

-->

![pkmn_sots_17](https://user-images.githubusercontent.com/8502545/36708134-e378d7b4-1b71-11e8-9864-6bbe658d0c12.png)

Das soll wahrscheinlich nicht

**Comment by SBird1337** [comment]
rework...
