### ISSUE TITLE
Wald von Yelnia, kaputte Textbox

### ISSUE THREAD

**Issue by ipatix** [SBird1337/source_of_the_sovereign#81]
![pkmn_sots_18](https://user-images.githubusercontent.com/8502545/36708337-d98391ee-1b72-11e8-8f0e-256c88d25bff.png)

**Comment by Dragonflysots** [comment]
@ipatix ähh, ok das schaue ich mir später an

**Comment by SBird1337** [comment]
nach dem rework nicht mehr relevant

**Comment by ipatix** [comment]
Nach welchem Rework?
