### ISSUE TITLE
unpassender Möbelwagen Sound

### ISSUE THREAD

**Issue by ipatix** [SBird1337/source_of_the_sovereign#82]
![pkmn_sots_19](https://user-images.githubusercontent.com/8502545/36708451-5be429dc-1b73-11e8-8b8e-ae39d96ee1c1.png)

Wenn sich die Höhle öffnet hört man kurz den Sound vom Möbelwagen aus Smaragd.

**Comment by Dragonflysots** [comment]
@ipatix Haste was besseres parat? Hab nichts gefunden...

**Comment by ipatix** [comment]
Welches ist das Skript dazu? Dann würde ich mal diverse Sachen ausprobieren

**Comment by Dragonflysots** [comment]
@ipatix "...\source_of_the_sovereign\sots-private\map\script\7_Urbania_City_Indoor\12_Hoehle_der_Weachter_Eingang\0_Levelscript.s"

**Comment by ipatix** [comment]
db4c3b0a92d5c942e59a406a83f1d6386659e50f
